// src/App.vue
<template>
  <main>
    <p>Hi, please enter your name:</p>
    <p>First: <input v-model="firstName" /></p>
    <p>Last: <input v-model="lastName" /></p>
    <p>{{ fullName }}</p>
    <p><button v-on:click="reset">Reset</button></p>
  </main>
</template>

<script>
export default {
  data() {
    return {
      firstName: '',
      lastName: ''
    }
  },
  computed: {
    fullName() {
      return this.firstName + ' ' + this.lastName
    }
  },
  methods: {
    reset() {
      this.firstName = ''
      this.lastName = ''
    }
  }
}
</script>

<style scoped>
main {
  font-family: Arial, Helvetica, sans-serif;
  padding: 1em;
  max-width: 240px;
  margin: 0 auto;
  background-color:#eee;
}
</style>

// src/App.svelte
<script>
	let firstName = '';
	let lastName = '';

	$: fullName = firstName + ' ' + lastName;

	function reset() {
		firstName = '';
		lastName = '';
	}
</script>

<main>
	<p>Hi, please enter your name:</p>
	<p>First: <input bind:value={firstName} /></p>
	<p>Last: <input bind:value={lastName} /></p>
	<p>{ fullName }</p>
	<p><button on:click={reset}>Reset</button></p>
</main>

<style>
	main {
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
		background-color:#eee;
	}
</style>
